### ISSUE TITLE
Guide for plugin

### ISSUE THREAD

**Issue by rayene01** [Frozen-Projects/FF_MQTT_Sync#1]
Hello, I'm interested in this plugin to use it in my project. Is there any guide for how to use and install it?

**Comment by ffreality** [comment]
I don't have time to make tutorial or documentation for it.
Just look at plugin's content folder. you will see a blueprint sample. Just change them with your MQTT broker's informations.

Error logs exported as json to blueprint.
"Description" field will you give description about error.
"ErrorCode" field will give you MQTT error code.

Btw. this is Unreal Engine plugin. Not Flutter or Unity. I assume that you know this and how to install a plugin to UE project.
