### ISSUE TITLE
Any documentation how to use this available?

### ISSUE THREAD

**Issue by mhoppebeyonity** [Frozen-Projects/FF_MQTT_Sync#2]
HEllo and thank you for contributing. 

I was happy to finf a MQTT for Unreal, was happy to compile it, but now I don't know how to use this. IS there any dokumentation how to set this thing up?

Thank you!

**Comment by ffreality** [comment]
https://github.com/FF-Plugins-Active/FF_MQTT_Sync/issues/1#issuecomment-2441434020
