### ISSUE TITLE
FF_OpenSSL Error

### ISSUE THREAD

**Issue by NastyPastie1** [Frozen-Projects/FF_MQTT_Sync#3]
Hi @ffreality 

I get FF_OpenSSL Error when i try to launch the project files. I cannot find FF_OpenSSL anywhere. It is saying its a requirement for the library of both the FF_MQTT_Sync and FF_MQTT_Async.

I am running UE 5.3.2 so i had to remove the following:
        UndefinedIdentifierWarningLevel = WarningLevel.Off;
From the Build.cs files. 

Would you be able to point me in the right direction.

Thank you.

**Comment by NastyPastie1** [comment]
I dont know if im barking up the wrong tree however ive done the following:

`using System;
using System.IO;
using UnrealBuildTool;

public class FF_MQTT_Sync : ModuleRules
{
    public FF_MQTT_Sync(ReadOnlyTargetRules Target) : base(Target)
    {
        PCHUsage = ModuleRules.PCHUsageMode.UseExplicitOrSharedPCHs;
        bEnableExceptions = true;

        PublicDependencyModuleNames.AddRange(
            new string[]
            {
                "Core",
                "paho_c",
                "paho_c_sync",
            }
        );

        PrivateDependencyModuleNames.AddRange(
            new string[]
            {
                "CoreUObject",
                "Engine",
                "Slate",
                "SlateCore",
                "Json",
                "JsonUtilities",
                "JsonBlueprintUtilities"
            }
        );

        string OpenSSLPath = Path.Combine(EngineDirectory, "Source", "ThirdParty", "OpenSSL", "1.1.1t");
        string OpenSSLInclude = Path.Combine(OpenSSLPath, "include", "Win64", "VS2015", "openssl");
        string OpenSSLLibPath = Path.Combine(OpenSSLPath, "lib", "Win64", "VS2015", "Release");
        PublicIncludePaths.Add(OpenSSLInclude);
        PublicAdditionalLibraries.Add(Path.Combine(OpenSSLLibPath, "libssl.lib"));
        PublicAdditionalLibraries.Add(Path.Combine(OpenSSLLibPath, "libcrypto.lib"));

        DynamicallyLoadedModuleNames.AddRange(
            new string[]
            {
            }
        );
    }
}`
I need to do some testing but it compiles now :)

**Comment by ffreality** [comment]
`FF_OpenSSL` is one of my private plugins which I don't want to share.
Because it has some important functions.

I don't remember I added it to satisfy `OpenSSL` requirements. But `MQTT` plugin's itself doesn't use any function from it. `Paho` wants to see it, that's all.

So, you can delete that plugin requirements and get it from Engine's third party directory.
I am not on my computer but you are on correct path.

Thanks for pointing it. I can fix that and my other public plugin's private dependencies in today (or worst tomorrow)

**Comment by NastyPastie1** [comment]
Not a problem, i can see that its loading the blueprint nodes etc now which is nice however trying to use the uassets you have provided for the BPs templates has been a challenge. Im downloading 5.5.1 now to try and gain access to the BP's as they need to be migrated, but they need to be on the same version that it was made on. 
If possible any chance you can give screenshots of these blueprints.

**Comment by ffreality** [comment]
> Not a problem, i can see that its loading the blueprint nodes etc now which is nice however trying to use the uassets you have provided for the BPs templates has been a challenge. Im downloading 5.5.1 now to try and gain access to the BP's as they need to be migrated, but they need to be on the same version that it was made on. If possible any chance you can give screenshots of these blueprints.

of course. I think blueprint paste bin will work

**Comment by NastyPastie1** [comment]
Perfect, thanks :)

**Comment by ffreality** [comment]
> Perfect, thanks :)

https://blueprintue.com/blueprint/tyjl3y62/
https://blueprintue.com/blueprint/7i2hjgct/

**Comment by ffreality** [comment]
> I dont know if im barking up the wrong tree however ive done the following:
> 
> `using System; using System.IO; using UnrealBuildTool;
> 
> public class FF_MQTT_Sync : ModuleRules { public FF_MQTT_Sync(ReadOnlyTargetRules Target) : base(Target) { PCHUsage = ModuleRules.PCHUsageMode.UseExplicitOrSharedPCHs; bEnableExceptions = true;
> 
> ```
>     PublicDependencyModuleNames.AddRange(
>         new string[]
>         {
>             "Core",
>             "paho_c",
>             "paho_c_sync",
>         }
>     );
> 
>     PrivateDependencyModuleNames.AddRange(
>         new string[]
>         {
>             "CoreUObject",
>             "Engine",
>             "Slate",
>             "SlateCore",
>             "Json",
>             "JsonUtilities",
>             "JsonBlueprintUtilities"
>         }
>     );
> 
>     string OpenSSLPath = Path.Combine(EngineDirectory, "Source", "ThirdParty", "OpenSSL", "1.1.1t");
>     string OpenSSLInclude = Path.Combine(OpenSSLPath, "include", "Win64", "VS2015", "openssl");
>     string OpenSSLLibPath = Path.Combine(OpenSSLPath, "lib", "Win64", "VS2015", "Release");
>     PublicIncludePaths.Add(OpenSSLInclude);
>     PublicAdditionalLibraries.Add(Path.Combine(OpenSSLLibPath, "libssl.lib"));
>     PublicAdditionalLibraries.Add(Path.Combine(OpenSSLLibPath, "libcrypto.lib"));
> 
>     DynamicallyLoadedModuleNames.AddRange(
>         new string[]
>         {
>         }
>     );
> }
> ```
> 
> }` I need to do some testing but it compiles now :)

Don't need to add whole path. Just add `"OpenSSL"` (including quotes) to `Public Dependency Modules`. Unreal already exposed it as module.
https://github.com/EpicGames/UnrealEngine/blob/release/Engine/Source/ThirdParty/OpenSSL/OpenSSL.Build.cs

I updated it.
